version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:12
    volumes:
      - db-data:/var/run/postgresql/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      #python:
      #build: .
      #restart: on-failure

  book_service:
    container_name: book
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  db-data: